name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:


    - name: get access token
      shell: bash
      run: | 
        ACCESS_TOKEN=$(curl -i --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=$KEYID" \
        --data-urlencode "client_secret=$KEYSECRET" \
        "https://auth.iam.sbercloud.ru/auth/system/openid/token"\
        | jq -r '.access_token')
        
         echo "ACCESS_TOKEN=$ACCESS_TOKEN"

        
      env:
        KEYID: ${{ secrets.EVOAR_KEYID }}
        KEYSECRET: ${{ secrets.EVOAR_KEYSECRET }}
  
