name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:


    - name: get access token
      run: | 
        TOKEN=$(curl -i --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=$KEYID" \
        --data-urlencode "client_secret=$KEYSECRET" \
        "https://auth.iam.sbercloud.ru/auth/system/openid/token"\
        ) \
        echo "echo full token"
        echo $TOKEN
        
      env:
        KEYID: ${{ secrets.EVOAR_KEYID }}
        KEYSECRET: ${{ secrets.EVOAR_KEYSECRET }}
  
