name: Create Container App

on:
  workflow_dispatch:
  push:
    paths:
     - '!.github/workflows/**'
     - '.github/workflows/create-container-app.yml'

env:
  public_api: 'https://containers.api.cloud.ru/v1beta/containers'
  registry_uri: 'cr.cloud.ru/a360ece4-3fef-4d69-b9f9-8f55a43eeaf4' # 'import.cr.cloud.ru'
  image_name: 'aspnetapp@sha256:079d0f3df65893ef8a2bcf65108781d8fa7a2e3dd2f2606159d376a78026c6d0'
  project_id: '06363f30-bde4-41a2-a96f-398bf8bd830e'
  ca_name: 'mibontest-2024'
  container_id: 311eb426-e585-4032-8062-68421e338e18
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get some vars
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        
      - name: Create Evolution Container App
        uses: ./.github/actions/create-update-eca
        with:
          client_id: ${{ secrets.EVOAR_KEYID }}
          client_secret:  ${{ secrets.EVOAR_KEYSECRET }}
          registry_uri: ${{ env.registry_uri }}
          image_name: ${{ env.image_name }}
          project_id: ${{ env.project_id }}
          name: ${{ env.ca_name }}-${{env.sha_short}}
