name: Create Container App

on:
  push:
    paths:
     - '!.github/workflows/**'
     - '.github/workflows/create-container-app.yml'

env:
  public_api: 'https://containers.api.cloud.ru/v1beta/containers'
  registry_uri: 'cr.cloud.ru/a360ece4-3fef-4d69-b9f9-8f55a43eeaf4' # 'import.cr.cloud.ru'
  image_name: 'aspnetapp@sha256:079d0f3df65893ef8a2bcf65108781d8fa7a2e3dd2f2606159d376a78026c6d0'
  project_id: '06363f30-bde4-41a2-a96f-398bf8bd830e'
  ca_name: 'demoapp012345678901'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get access token & create container app
      shell: bash
      run: | 
       # https://cloud.ru/ru/docs/kubernetes-evolution/ug/topics/api-ref__authentication.html 
        ACCESS_TOKEN=$(curl --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=$KEYID" \
        --data-urlencode "client_secret=$KEYSECRET" \
        "https://auth.iam.sbercloud.ru/auth/system/openid/token" \
        | jq -r '.access_token')

        
         echo "ACCESS_TOKEN==$ACCESS_TOKEN" \

        curl --location $public_api \
        --header 'Content-Type: application/json' \
        --header "Authorization: Bearer $ACCESS_TOKEN" \
        --data-raw '{ 
              "project_id": "${{ env.project_id}}",
              "name": "${{ env.ca_name }}",
              "resources": {
                  "limits": {
                      "cpu": "0.1",
                      "memory": "256Mi"
                  },
                  "requests": {
                      "cpu": "0.1",
                      "memory": "256Mi"
                  }
              },
              "scaling": {
                  "min_instance_count": 0,
                  "max_instance_count": 1,
              },
              "timeout": "600s",
              "image": "${{ env.registry_uri }}/${{ env.image_name }}",
              "port": 8080,
              "command": "[]",
              "command_args": "[]",
              "protocol": "http_1"
          }'

          curl -X DELETE "https://containers.api.cloud.ru/v1beta/containers?project_id=${{ env.project_id}}&id=ef291e9f-0d36-48fa-a382-b297310acafe" \
               -H 'Authorization: Bearer $TOKEN'

          curl --location --request PATCH $public_api \
        --header 'Content-Type: application/json' \
        --header "Authorization: Bearer $ACCESS_TOKEN" \
        --data-raw '{ 
              "project_id": "${{ env.project_id}}",
              "name": "${{ env.ca_name }}",
              "resources": {
                  "limits": {
                      "cpu": "0.1",
                      "memory": "256Mi"
                  },
                  "requests": {
                      "cpu": "0.1",
                      "memory": "256Mi"
                  }
              },
              "scaling": {
                  "min_instance_count": 0,
                  "max_instance_count": 5,
              },
              "timeout": "600s",
              "image": "${{ env.registry_uri }}/${{ env.image_name }}",
              "port": 8080,
              "command": "[]",
              "command_args": "[]",
              "protocol": "http_1"
          }'
        
      env:
        KEYID: ${{ secrets.EVOAR_KEYID }}
        KEYSECRET: ${{ secrets.EVOAR_KEYSECRET }}
  
