name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Running Oryx to generate a Dockerfile
      id: oryx
      uses: microsoft/oryx/actions/oryx-dockerfile@main
      with: 
         platform: "nodejs"
         platform-version: 20.11.1
         source-directory: app

    - name: Build and push Backend container image to cloud evolution registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: latest
        platform: linux/amd64
        provenance: false
        file: ${{ steps.oryx.outputs.dockerfile-path }}
        context: ./
