name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Running Oryx to generate a Dockerfile
      id: oryx
      uses: microsoft/oryx/actions/oryx-dockerfile@main
      with: 
         platform: "nodejs"
         source-directory: app
