name: Init Containers Demo

on:
  workflow_dispatch:
  push:
    paths:
     - '!.github/workflows/**'
     - '.github/workflows/init-containers-demo.yml'

env:
  registry_uri: 'cr.cloud.ru/a360ece4-3fef-4d69-b9f9-8f55a43eeaf4' # 'import.cr.cloud.ru'
  image_name: 'aspnetapp@sha256:079d0f3df65893ef8a2bcf65108781d8fa7a2e3dd2f2606159d376a78026c6d0'
  project_id: '06363f30-bde4-41a2-a96f-398bf8bd830e'
  ca_name: 'mibon'
  container_id: 311eb426-e585-4032-8062-68421e338e18
  EVOAR_URI: demo1204.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get some vars
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.EVOAR_URI }}
          username: ${{ secrets.EVOAR_KEYID }}
          password: ${{ secrets.EVOAR_KEYSECRET }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push container image to cloud evolution registry
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ${{ env.EVOAR_URI }}/nc-init:${{ env.sha_short }}
          file: init-demo/nc-init/Dockerfile
          context: ./
