name: Trigger auto deployment for mibon-frontedapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mibon-frontedapp-AutoDeployTrigger-98094766-8c1f-4822-9a80-b253c70a791a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to cloud evolution container registry
        uses: docker/login-action@v1
        with:
          registry: cr.cloud.ru/887656ef-a8db-4cb2-9786-13f9b3686d34/
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}

      - name: Build and push container image to cloud evolution registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: cr.cloud.ru/887656ef-a8db-4cb2-9786-13f9b3686d34/mibon-frontedapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./
          
      - name: Log in to azure container registry
        uses: docker/login-action@v1
        with:
          registry: bondcr.azurecr.io
          username: ${{ secrets.AZ_CR_LOGIN }}
          password: ${{ secrets.AZ_CR_PWD }}

      - name: Build and push container image to cloud evolution registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bondcr.azurecr.io/mibon-frontedapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./
          
 
