name: Trigger auto deployment for mibon-frontedapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mibon-frontedapp-AutoDeployTrigger-98094766-8c1f-4822-9a80-b253c70a791a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mibon2.azurecr.io
          username: ${{ secrets.MIBONFRONTEDAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MIBONFRONTEDAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mibon2.azurecr.io/mibon-frontedapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MIBONFRONTEDAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mibon-frontedapp -g mibon5test --server mibon2.azurecr.io --username  ${{ secrets.MIBONFRONTEDAPP_REGISTRY_USERNAME }} --password ${{ secrets.MIBONFRONTEDAPP_REGISTRY_PASSWORD }}
            az containerapp update -n mibon-frontedapp -g mibon5test --image mibon2.azurecr.io/mibon-frontedapp:${{ github.sha }}
