name: Test Build Pack

on:
  push:
    branches: [ "master" ]
    paths:
      - '!.github/workflows/**'
      - '.github/workflows/test-build-pack.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install pack CLI on non-Windows runner
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.31.0/pack-v0.31.0-${{ runner.os }}.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

      - id: package
        shell: bash
        env: 
          REPO: docker.io/mikhail2k15 
        run: |
          #!/usr/bin/env bash
          pack build test_img --path ./app --builder heroku/buildpacks:20 
    
    #- uses: actions/checkout@v4
    
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
